format = """
$directory\
$git_branch\
$git_status\
$status\
$all$character"""

add_newline = true

[directory]
style = "bold fg:#61afef"
format = "[ $read_only$path ]($style)"
read_only = " "
fish_style_pwd_dir_length = 3
truncate_to_repo = true
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
style = "bold fg:#818cf8"
format = "on [$symbol$branch]($style)"
symbol = " "

[git_status]
style = "bold fg:#a78bfa"
format = "[$all_status$ahead_behind ]($style)"
stashed = "  ${count}"
ahead = " ﲗ ${count}"
behind = " ﲔ ${count}"
diverged = " 李 ${ahead_count} ${behind_count}"
conflicted = " ${count}"
deleted = "  ${count}"
renamed = "﫦${count}"
modified = " 凜${count}"
staged = "  ${count}"
untracked = "  ${count}"

[status]
disabled = true
symbol = " "
format = "[ $symbol$status ]($style)"
style = " fg:#e06c75 "

[character]
format = " $symbol "
success_symbol = "[❯](bold #98c379)"
error_symbol = "[❯](bold #e06c75)"
vicmd_symbol = "[⬢](bold #98c379)"

[jobs]
format = "[ $symbol$number]($style)"

[package]
disabled = true
[java]
disabled = true
[nodejs]
disabled = true
[python]
format = '[${symbol}(\($virtualenv\) )]($style)'
[c]
disabled = true
[battery]
disabled = true
